### ISSUE TITLE
Oportunidad de mejora, crea una funcion validar() 

### ISSUE THREAD

**Issue by aaron-developer25** [Ruth2002Casilla/MainSystem-Android#9]
https://github.com/Ruth2002Casilla/MainSystem-Android/blob/2d1ea3fa31961df879fe5d08830ea7076385e9ec/app/src/main/java/edu/ucne/composedemo/mainsystemtickets/presentation/screenEntity/tickets/TicketViewModel.kt#L36C1-L78C6

Sería interesante reducir la cantidad de código creando una función Validar() que cumpla la función de validar los campos, así ahorrarías código duplicidad de codigo tanto en guardar como en actualizar.

**Comment by Ruth2002Casilla** [comment]
No me es posible. No puedo hacer el cambio ya que me genera error sobre error
